# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "tfe-v2-states-037638919006"
    dynamodb_table = "tfe-v2-lock-table"
    encrypt        = true
    key            = "encryption/terraform.tfstate"
    region         = "eu-central-1"
  }
}
